
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";

export const metadata = {
  title: "Buymyoldphone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Analytics/>
      </body>
    </html>
  );
}
